apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snipe-it
  namespace: "{{ env['K8S_NAMESPACE'] }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-production
    cert-manager.io/tls-acme: "true"
spec:
  ingressClassName: public
  rules:
  - host: "{{ env['INGRESS_URL'] }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuma2
            port:
              number: 3001
  tls:
  - hosts:
    - "{{ env['INGRESS_URL'] }}"
    secretName: snipe-it-tls