apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: snipe-it-postgres
  namespace: "{{ env['K8S_NAMESPACE'] }}"
spec:
  teamId: "snipe-it"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    postgres:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    snipe-it: postgres  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "17"